name: {{PROJECT NAME}} CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t {{PROJECT TAG}} -f Dockerfile .
      - name: Tags
        run: |
          docker tag {{PROJECT TAG}} ${{ secrets.DOCKER_USER }}/{{PROJECT TAG}}:${{ github.sha }}
          docker tag {{PROJECT TAG}} ${{ secrets.DOCKER_USER }}/{{PROJECT TAG}}:beta
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/{{PROJECT TAG}}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/{{PROJECT TAG}}:latest
